export enum EnvVarNames {
  COGNITO_CLIENT_ID = 'COGNITO_CLIENT_ID',
  COGNITO_USER_POOL_ID = 'COGNITO_USER_POOL_ID',
  VPA_GAME_TABLE_NAME = 'VPA_GAME_TABLE_NAME',
  VPA_STATE_API_GW_URL = 'VPA_STATE_API_GW_URL',
  VPA_STATE_BUCKET_NAME = 'VPA_STATE_BUCKET_NAME',
}
