name: app-test

on:
  pull_request:
    paths:
      - 'packages/frontend/**'
      - '!packages/frontend/docs/**'
      - '!packages/frontend/public/**'

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm ci -w frontend
      - run: npm list
      - run: npm run build:frontend
      - run: npm run lint:frontend
      - run: npm run test:frontend
  check-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm ci -w frontend
      - run: npm run checkFormat:frontend

