name: backend-test

on:
  pull_request:
    paths:
      - 'packages/backend/**'

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm ci -include-workspace-root -w backend -w api-types
      - run: npm run lint:backend
      - run: npm run test:backend
  check-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm ci -include-workspace-root -w backend
      - run: npm run checkFormat:backend
