name: infra-deploy

on:
  push:
    branches:
      - main
    paths:
      - 'packages/infra/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm ci -include-workspace-root -w infra -w backend
      - run: npm run deploy:infra:all
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  notify:
    runs-on: ubuntu-latest
    needs:
      - deploy
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - env:
          DISCORD_WEBHOOK: ${{ secrets.DS_DEV_DIARY_WEBHOOK_URL }}
          DISCORD_EMBEDS: '[{"title": "${{github.workflow}} Failed",  "color": 13840175}]'
        uses: Ilshidur/action-discord@master
